name: Calculator CI

on:
  push:
    branches:
      - main
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Verify Python
      run: python --version
    
    - name: Run Calculator Program
      run: python Calculator.py
